version: '3.1'

services:
  db:
    container_name: db
    restart: always
    image: postgres:13
    volumes:
      - ./.docker/db/pgdata:/pgdata
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "db"
      PGDATA: /pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 30s
      retries: 3

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 5000:8080