// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package ova_conference_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	zlog "github.com/rs/zerolog/log"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TrackClient is the client API for Track service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrackClient interface {
	CreateTrack(ctx context.Context, in *TrackDescription, opts ...grpc.CallOption) (*TrackID, error)
	DescribeTrackByID(ctx context.Context, in *TrackID, opts ...grpc.CallOption) (*TrackDescription, error)
	GetTrackID(ctx context.Context, in *TrackDescription, opts ...grpc.CallOption) (*TrackID, error)
	GetRegisteredTracks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TrackDescription, error)
	RemoveTrackByID(ctx context.Context, in *TrackID, opts ...grpc.CallOption) (*Empty, error)
}

type trackClient struct {
	cc grpc.ClientConnInterface
}

func NewTrackClient(cc grpc.ClientConnInterface) TrackClient {
	return &trackClient{cc}
}

func (c *trackClient) CreateTrack(ctx context.Context, in *TrackDescription, opts ...grpc.CallOption) (*TrackID, error) {
	out := new(TrackID)
	err := c.cc.Invoke(ctx, "/ova.track.api.Track/CreateTrack", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackClient) DescribeTrackByID(ctx context.Context, in *TrackID, opts ...grpc.CallOption) (*TrackDescription, error) {
	out := new(TrackDescription)
	err := c.cc.Invoke(ctx, "/ova.track.api.Track/DescribeTrackByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackClient) GetTrackID(ctx context.Context, in *TrackDescription, opts ...grpc.CallOption) (*TrackID, error) {
	out := new(TrackID)
	err := c.cc.Invoke(ctx, "/ova.track.api.Track/GetTrackID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackClient) GetRegisteredTracks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TrackDescription, error) {
	out := new(TrackDescription)
	err := c.cc.Invoke(ctx, "/ova.track.api.Track/GetRegisteredTracks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackClient) RemoveTrackByID(ctx context.Context, in *TrackID, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/ova.track.api.Track/RemoveTrackByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrackServer is the server API for Track service.
// All implementations must embed UnimplementedTrackServer
// for forward compatibility
type TrackServer interface {
	CreateTrack(context.Context, *TrackDescription) (*TrackID, error)
	DescribeTrackByID(context.Context, *TrackID) (*TrackDescription, error)
	GetTrackID(context.Context, *TrackDescription) (*TrackID, error)
	GetRegisteredTracks(context.Context, *Empty) (*TrackDescription, error)
	RemoveTrackByID(context.Context, *TrackID) (*Empty, error)
	mustEmbedUnimplementedTrackServer()
}

// UnimplementedTrackServer must be embedded to have forward compatible implementations.
type UnimplementedTrackServer struct {
}

func (UnimplementedTrackServer) CreateTrack(context.Context, *TrackDescription) (*TrackID, error) {
	zlog.Print("Create track called")
	return nil, status.Errorf(codes.Unimplemented, "method CreateTrack not implemented")
}
func (UnimplementedTrackServer) DescribeTrackByID(context.Context, *TrackID) (*TrackDescription, error) {
	zlog.Print("Describe track id called")
	return nil, status.Errorf(codes.Unimplemented, "method DescribeTrackByID not implemented")
}
func (UnimplementedTrackServer) GetTrackID(context.Context, *TrackDescription) (*TrackID, error) {
	zlog.Print("Get track id called")
	return nil, status.Errorf(codes.Unimplemented, "method GetTrackID not implemented")
}
func (UnimplementedTrackServer) GetRegisteredTracks(context.Context, *Empty) (*TrackDescription, error) {
	zlog.Print("Get registered tracks called")
	return nil, status.Errorf(codes.Unimplemented, "method GetRegisteredTracks not implemented")
}
func (UnimplementedTrackServer) RemoveTrackByID(context.Context, *TrackID) (*Empty, error) {
	zlog.Print("Remove track by id called")
	return nil, status.Errorf(codes.Unimplemented, "method RemoveTrackByID not implemented")
}
func (UnimplementedTrackServer) mustEmbedUnimplementedTrackServer() {}

// UnsafeTrackServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrackServer will
// result in compilation errors.
type UnsafeTrackServer interface {
	mustEmbedUnimplementedTrackServer()
}

func RegisterTrackServer(s grpc.ServiceRegistrar, srv TrackServer) {
	s.RegisterService(&Track_ServiceDesc, srv)
}

func _Track_CreateTrack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrackDescription)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackServer).CreateTrack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ova.track.api.Track/CreateTrack",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackServer).CreateTrack(ctx, req.(*TrackDescription))
	}
	return interceptor(ctx, in, info, handler)
}

func _Track_DescribeTrackByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrackID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackServer).DescribeTrackByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ova.track.api.Track/DescribeTrackByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackServer).DescribeTrackByID(ctx, req.(*TrackID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Track_GetTrackID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrackDescription)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackServer).GetTrackID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ova.track.api.Track/GetTrackID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackServer).GetTrackID(ctx, req.(*TrackDescription))
	}
	return interceptor(ctx, in, info, handler)
}

func _Track_GetRegisteredTracks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackServer).GetRegisteredTracks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ova.track.api.Track/GetRegisteredTracks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackServer).GetRegisteredTracks(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Track_RemoveTrackByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrackID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackServer).RemoveTrackByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ova.track.api.Track/RemoveTrackByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackServer).RemoveTrackByID(ctx, req.(*TrackID))
	}
	return interceptor(ctx, in, info, handler)
}

// Track_ServiceDesc is the grpc.ServiceDesc for Track service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Track_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ova.track.api.Track",
	HandlerType: (*TrackServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTrack",
			Handler:    _Track_CreateTrack_Handler,
		},
		{
			MethodName: "DescribeTrackByID",
			Handler:    _Track_DescribeTrackByID_Handler,
		},
		{
			MethodName: "GetTrackID",
			Handler:    _Track_GetTrackID_Handler,
		},
		{
			MethodName: "GetRegisteredTracks",
			Handler:    _Track_GetRegisteredTracks_Handler,
		},
		{
			MethodName: "RemoveTrackByID",
			Handler:    _Track_RemoveTrackByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/api.proto",
}
